### PR TITLE
Fix Commit logs formatting issues

### LINKED ISSUE #13: Manually format the commit logs for displaying it in Github Markdown
🤔 https://github.com/Mieraidihaimu/GeneratePR/pull/12 change does solve lots of critical issue. 
However it created a very tiny bugs 😂  
The log commits are without special character `* `, hence is bit less readable. Maybe I need to add markdown character manually `-` on each line changes.

### PR DESCRIPTION
**Pull request by Mieraidihaimu**
# Related links

close https://github.com/Mieraidihaimu/GeneratePR/issues/13

# Why?

As pet ticket above, we need to fix the defect in this release.

# How?

Changes included:
- Add Commitlogsformatter Helper
- User Formatter To Have Pretty Printed Commits
- Fix Compiler Error :Joy

### CODE REVIEW

File: Sources/GeneratePR/Helper/CommitLogsFormatter.swift [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+    }
+
+
+    private static func formatLineIfNeeded(_ line: String) -> String {
+        guard line.prefix(2) != linePrefixCharacter else { return line }
+        if #available(macOS 10.11, *) {
+            return linePrefixCharacter + line.localizedCapitalized
+        } else {
+            return linePrefixCharacter + line
+        }
```
Comment (Mieraidihaimu) [inline Sources/GeneratePR/Helper/CommitLogsFormatter.swift]: Redundent to capitalised every letter 😂 
```suggestion
        return linePrefixCharacter + line
```
